# Project One:
Project Description

### Tasks
- [ ] Exploration     
- [ ] Explore the dataset  
- [ ] Research questions  
    - [ ] 3 - 5: Find some quenstions
        - [] How many attack per gender 
            - [] Separate per gender and quantity
        - [] How many attacks per species
            - [] separate by species, quantity and year
        - [] total cases
            - [] by country, area, location and year
            - [] data name: local_cases
        - [] The most dangerous location per activity
            - [] by activity, country, area and location      
    - [ ] Messy: transforming  
    - [ ] Visualizations: range of 3 - 5 
    
- [ ] DELIVER 06-02-2024
    - [ ] Github repo
    - [ ] Present: canva presentations (open link)
    - [ ] Max 5min
    - [ ]Tuesday 9am
     
    
    
    
### Completed Column ✓
- [x] Project on github: csv  
- [x] Open notebok: csv

#

### Extracao de dados
    - Total de ataques
        - remover todos os valores vazios da coluna Location
        - passar a coluna editada para um novo DF
    - Total de ataques por area
        - remover os valores vazios e duplicados
        - passar a coluna editada para um novo DF
    - Total de ataques por Pais
        - remover os valores vazios e duplicados
        - passar a coluna editada para um novo DF 
    - Prepara a coluna Year
        - remover todos os valores vazios da coluna
        - Transformar em INT

In [ ]:
### Describing a numeric Series
s = pd.Series([1, 2, 3])
s.describe()
count    3.0 # Número total de elementos na série categórica
mean     2.0 # a media da soma total dos valores 
std      1.0 # Medida de dispersão que indica o quão longe os valores do conjunto estão da média
min      1.0 # o menor valor 
25%      1.5 # O valor que divide os 25% menores valores da série numérica para esquerda
50%      2.0 # O valor que divide a série numérica ao meio
75%      2.5 # O valor que divide os 75% menores valores da série numérica para direita
max      3.0 # o maior valor
dtype: float64

count: Número total de elementos em um conjunto de dados. Indica a contagem total de observações ou itens.

mean: (média): A média aritmética dos valores em um conjunto de dados. Obtida somando todos os valores e dividindo pelo número total de elementos.

std: (desvio padrão): Medida de dispersão que indica o quão longe os valores do conjunto estão da média. Um desvio padrão mais alto indica maior dispersão.

min: (mínimo): O valor mais baixo em um conjunto de dados, representando o menor elemento.

25%: (primeiro quartil): O valor que divide os 25% menores valores da série numérica. Também é conhecido como primeiro quartil ou quartil inferior.

50%: (mediana): O valor que divide a série numérica ao meio, deixando 50% dos valores abaixo e 50% acima. Também é conhecido como mediana.

75%: (terceiro quartil): O valor que divide os 75% menores valores da série numérica. Também é conhecido como terceiro quartil ou quartil superior.

max: (máximo): O valor mais alto em um conjunto de dados, representando o maior elemento.

In [ ]:
### Describing a categorical Series
s = pd.Series(['a', 'a', 'b', 'c'])
s.describe()
count     4 # Número total de elementos na série categórica
unique    3 # Número de valores únicos na série categórica
top       a # O valor mais frequente (ou categoria mais comum)
freq      2 # A frequência do valor mais comum na série categórica
dtype: object

count: Número total de elementos na série categórica. Indica a contagem total de observações ou itens na série.

unique: Número de valores únicos na série categórica. Representa a quantidade de categorias distintas presentes na série.

top: O valor mais frequente (ou categoria mais comum) na série categórica. Indica a categoria que ocorre com mais frequência.

freq: A frequência do valor mais comum na série categórica. Representa o número de ocorrências da categoria mais frequente.

In [1]:
### Describing a DataFrame. By default only numeric fields are returned.
df = pd.DataFrame({'categorical': pd.Categorical(['d', 'e', 'f']),
                   'numeric': [1, 2, 3],
                   'object': ['a', 'b', 'c']
                   })
df.describe()
       numeric
count      3.0 # Número total de elementos na coluna
mean       2.0 #  média aritmética dos valores na coluna
std        1.0 # O desvio padrão dos valores na coluna
min        1.0 # O valor mínimo na coluna
25%        1.5 # O valor que divide os 25% menores valores na coluna
50%        2.0 # O valor que divide a coluna ao meio
75%        2.5 # O valor que divide os 75% menores valores na coluna
max        3.0 # O valor máximo na coluna

count: Número total de elementos na coluna. Neste caso, estamos olhando para a coluna "numeric" e há 3 elementos, indicado por "count: 3.0".

mean (média): A média aritmética dos valores na coluna "numeric". Para a coluna "numeric" neste DataFrame, a média é 2.0, indicado por "mean: 2.0".

std (desvio padrão): O desvio padrão dos valores na coluna "numeric". O valor 1.0 indica a quantidade de dispersão dos valores ao redor da média.

min (mínimo): O valor mínimo na coluna "numeric". No caso da coluna "numeric", o valor mínimo é 1.0.

25% (primeiro quartil): O valor que divide os 25% menores valores na coluna "numeric". Neste caso, 25% dos valores são menores ou iguais a 1.5.

50% (mediana): O valor que divide a coluna "numeric" ao meio. Também conhecido como mediana, neste caso é 2.0.

75% (terceiro quartil): O valor que divide os 75% menores valores na coluna "numeric". Neste caso, 75% dos valores são menores ou iguais a 2.5.

max (máximo): O valor máximo na coluna "numeric". No caso da coluna "numeric", o valor máximo é 3.0.

IndentationError: unexpected indent (2771123753.py, line 7)

In [ ]:
### Describing all columns of a DataFrame regardless of data type.
df.describe(include='all')  
       categorical  numeric object
count            3      3.0      3
unique           3      NaN      3
top              f      NaN      a
freq             1      NaN      1
mean           NaN      2.0    NaN
std            NaN      1.0    NaN
min            NaN      1.0    NaN
25%            NaN      1.5    NaN
50%            NaN      2.0    NaN
75%            NaN      2.5    NaN
max            NaN      3.0    NaN

count: Número total de elementos em cada coluna. Neste caso, temos 3 elementos na coluna "categorical", 3 elementos na coluna "numeric" e 3 elementos na coluna "object".

unique: Número de valores únicos em cada coluna. Para a coluna "categorical", há 3 valores únicos; para a coluna "numeric", não há um número específico de valores únicos (indicado por NaN); para a coluna "object", há 3 valores únicos.

top: O valor mais frequente em cada coluna. Para a coluna "categorical", o valor mais frequente é 'f'; para as outras colunas, é indicado como NaN.

freq: A frequência do valor mais comum em cada coluna. Para a coluna "categorical", 'f' ocorre 1 vez; para as outras colunas, é indicado como NaN.

mean (média): A média aritmética dos valores numéricos em cada coluna. Para a coluna "numeric", a média é 2.0; para as outras colunas, é indicado como NaN.

std (desvio padrão): O desvio padrão dos valores numéricos em cada coluna. Para a coluna "numeric", o desvio padrão é 1.0; para as outras colunas, é indicado como NaN.

min (mínimo): O valor mínimo em cada coluna. Para a coluna "numeric", o valor mínimo é 1.0; para as outras colunas, é indicado como NaN.

25%, 50%, 75%: Os percentis 25%, 50% (mediana) e 75% em cada coluna. Esses valores indicam a distribuição dos dados em cada coluna numérica. Para as colunas "numeric", esses valores são dados; para as outras colunas, são indicados como NaN.

max (máximo): O valor máximo em cada coluna. Para a coluna "numeric", o valor máximo é 3.0; para as outras colunas, é indicado como NaN.

In [2]:
### Describing a column from a DataFrame by accessing it as an attribute.
df.numeric.describe()
count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
Name: numeric, dtype: float64

ccount: Número total de elementos na coluna "numeric". Indica a contagem total de observações ou itens na coluna.

mean (média): A média aritmética dos valores na coluna "numeric". Obtida somando todos os valores e dividindo pelo número total de elementos.

std (desvio padrão): O desvio padrão dos valores na coluna "numeric". O desvio padrão é uma medida de dispersão que indica o quão longe os valores estão da média. Um desvio padrão mais alto indica maior dispersão.

min (mínimo): O valor mínimo na coluna "numeric". Representa o menor elemento presente na coluna.

25% (primeiro quartil): O valor que divide os 25% menores valores na coluna "numeric". Também é conhecido como primeiro quartil ou quartil inferior.

50% (mediana): O valor que divide a coluna "numeric" ao meio. Também conhecido como mediana.

75% (terceiro quartil): O valor que divide os 75% menores valores na coluna "numeric". Também é conhecido como terceiro quartil ou quartil superior.

max (máximo): O valor máximo na coluna "numeric". Representa o maior elemento presente na coluna.

Name: O nome da coluna que está sendo descrita, que é "numeric" neste caso.

dtype: O tipo de dados da coluna, que é 'float64' neste caso.

SyntaxError: invalid syntax (1659083470.py, line 3)

In [ ]:
### Including only numeric columns in a DataFrame description.
df.describe(include=[np.number])
       numeric
count      3.0
mean       2.0
std        1.0
min        1.0
25%        1.5
50%        2.0
75%        2.5
max        3.0

count: Número total de elementos na coluna "numeric". Indica a contagem total de observações ou itens na coluna.

mean (média): A média aritmética dos valores na coluna "numeric". Obtida somando todos os valores e dividindo pelo número total de elementos.

std (desvio padrão): O desvio padrão dos valores na coluna "numeric". O desvio padrão é uma medida de dispersão que indica o quão longe os valores estão da média. Um desvio padrão mais alto indica maior dispersão.

min (mínimo): O valor mínimo na coluna "numeric". Representa o menor elemento presente na coluna.

25% (primeiro quartil): O valor que divide os 25% menores valores na coluna "numeric". Também é conhecido como primeiro quartil ou quartil inferior.

50% (mediana): O valor que divide a coluna "numeric" ao meio. Também conhecido como mediana.

75% (terceiro quartil): O valor que divide os 75% menores valores na coluna "numeric". Também é conhecido como terceiro quartil ou quartil superior.

max (máximo): O valor máximo na coluna "numeric". Representa o maior elemento presente na coluna.

In [ ]:
### Including only string columns in a DataFrame description.

df.describe(include=[object])  
       object
count       3
unique      3
top         a
freq        1

count: Número total de elementos na coluna "object". Indica a contagem total de observações ou itens na coluna.

unique: Número de valores únicos na coluna "object". Representa a quantidade de categorias distintas presentes na coluna.

top: O valor mais frequente na coluna "object". Indica a categoria (ou string) que ocorre com mais frequência.

freq: A frequência do valor mais comum na coluna "object". Representa o número de ocorrências da categoria mais frequente.

In [ ]:
# Remover os valores NaN e converter para int, tratando valores não válidos
# Codigo
data['Year'] = pd.to_numeric(data['Year'], errors='coerce', downcast='integer')

    - data['Year']: Acessa a coluna 'Year' no DataFrame 'data'.

    - pd.to_numeric(...): 
        - Esta função do pandas é utilizada para converter argumentos para números. 
        - Neste caso, ela está sendo usada para converter os valores na coluna 'Year' para numéricos.

    - data['Year'] = pd.to_numeric(...): 
        - Atribui os valores convertidos de volta à coluna 'Year' no DataFrame 'data'.

    - errors='coerce': 
        - Este argumento especifica que, se houver algum valor na coluna 'Year' que não possa ser convertido para um número, ele deve ser substituído por NaN (Not a Number). 
        - Isso é útil para lidar com valores não numéricos ou valores ausentes.

    - downcast='integer': 
        - Este argumento indica que, se possível, o pandas deve downcast (reduzir a precisão) dos valores numéricos para o menor tipo de dados possível. 
        - Neste caso, está sendo especificado 'integer', o que significa que a pandas tentará representar os números como inteiros, se possível.

In [ ]:
# Filtrar os dados para do período de 2015 a 2018
filtered_data = data[(data['Year'] >= 2015) & (data['Year'] <= 2018)]
    - filtered_data esta recebendo duas condicionais 
        - Se DF 'Year' for maior que 2015 e se DF for menor que 2018

In [ ]:
# Identificar o valor da coluna com a maior frequência para cada ano
    # Legenda das colunas
        - coluna_principal = 'Species '
        - coluna_referencia = 'Year'
        - Count = 'index_redefinido'

# Codigo        
top_species_by_year = (
    filtered_data.groupby(['coluna_referencia', 'coluna_principal'])
    .size()
    .reset_index(name='index_redefinido')
    .sort_values(['coluna_referencia', 'index_redefinido'], ascending=[True, False])
    .drop_duplicates('coluna_referencia')
)

    - filtered_data.groupby(['coluna_referencia', 'coluna_principal']).size(): 
        - O conjunto de dados filtered_data é agrupado por duas colunas, 'Year' e 'Species', usando o método groupby. 
        - A função size() é aplicada para contar o número de ocorrências em cada combinação única de ano e espécie. 
        - O resultado é uma Série que mostra a contagem de ocorrências para cada combinação de ano e espécie.

    - .reset_index(name='index_redefinido'): 
        - O índice do DataFrame resultante da operação groupby é redefinido, e a Série resultante é convertida de volta em um DataFrame. 
        - A nova coluna que contém a contagem é nomeada como 'Count'.

    - .sort_values(['coluna_referencia', 'index_redefinido'], ascending=[True, False]): 
        - O DataFrame é ordenado primeiro pela coluna 'Year' em ordem ascendente e, em seguida, pela coluna 'Count' em ordem descendente. 
        - Isso é feito para que, dentro de cada ano, a espécie com a contagem mais alta apareça primeiro.

    - .drop_duplicates('coluna_referencia'): 
        - A função drop_duplicates é usada para manter apenas a primeira ocorrência de cada ano, removendo as duplicatas. 
        - Isso significa que para cada ano, apenas a espécie com a contagem mais alta será mantida no DataFrame final.

In [ ]:
# Criar um gráfico de barras
barplot = sns.barplot(x="Year", y="Count", hue="Species ", data=top_species_by_year)

# Adicionar rótulos e título
plt.xlabel('Species')
plt.ylabel('Count')
plt.title('Species with Highest Frequency of attacks from 2015 to 2018')

# Rotacionar rótulos do eixo x para melhor visualização (opcional)
plt.xticks(rotation=45, ha='right')

# Exibir o gráfico
plt.show()


    - barplot = sns.barplot(x="Year", y="Count", hue="Species ", data=top_species_by_year): 
        - Um gráfico de barras é criado usando a função barplot do Seaborn. 
        - Os argumentos 'x', 'y', e 'hue', especificam as variáveis para o eixo x, eixo y e a diferenciação de cores (nesse caso, as diferentes espécies), respectivamente. 
        - Os dados utilizados são do DF top_species_by_year, que foi previamente criado para conter a espécie com a maior frequência para cada ano.

    - plt.xlabel('Species'): 
        - Adiciona um rótulo ao eixo x, indicando que as barras representam diferentes espécies.

plt.ylabel('Count'): 
    - Adiciona um rótulo ao eixo y, indicando que as alturas das barras representam a contagem de ataques.

plt.title('Species with Highest Frequency of attacks from 2015 to 2018'): 
    - Adiciona um título ao gráfico, fornecendo uma descrição geral do que está sendo representado.

plt.xticks(rotation=45, ha='right'): 
    - Rotaciona os rótulos do eixo x em 45 graus para melhorar a legibilidade. 
    - O argumento ha='right' alinha os rótulos à direita para evitar sobreposições.

plt.show(): Exibe o gráfico.

## Pandas usual methods
```python
df.head() # prints the head, default 5 rows
df.tail() # set the tail, default 5 rows
df.describe() # statistical description
df.info() # df information
df.columns # show column
df.index # show index
df.dtypes # show column data types
df.plot() # make a plot
df.hist() # make a histogram
df.col.value_counts() # counts the unique values ​​of a column
df.col.unique() # returns unique values ​​from a column
df.copy() # copies the df
df.drop() # remove columns or rows (axis=0,1)
df.dropna() # remove nulls
df.fillna() # # to convert float NaN to 0
df.shape # dimensions of the df
df._get_numeric_data() # select numeric columns
df.rename() # rename columns
df.str.replace() # replace columns of strings
df.astype(dtype='float32') # change the data type
df.iloc[] # locate by index
df.loc[] # locate by element
df.transpose() # transposes the df
df.T
df.sample(n, frac) # sample from df
df.col.sum() # sum of a column
df.col.max() # maximum of a column
df.col.min() # minimum of one column
df[col] # select column
df.col
df.isnull() # null values
df.isna()
df.notna() # not null values
df.drop_duplicates() # remove duplicates
df.reset_index(inplace=True) # reset the index and overwrite
df.set_index() # tranforma a coluna em index da df
```

In [ ]:
### Tarefas 
- [x] Criar um arquivo test.ipynb.
- [x] Importar as bibliotecas
- [x] Exportar o .csv
- [x] Criar uma lista. DF
- [x] Verificar quantos objetos NaN tem na lista com .Info()
- [x] Limpar todos os valores NaN da lista com .dropan(how='all')
- [x] Verificar se os objetos NaN foram deletados da lista com .Info() 
- [x] Verificar o tipo das culonas ( Year, Country, Area e Location) com .types() 
- [x] Alterar o tipo da coluna ('Year')  para int com .df = df.astype(int) 
- [] Criar uma nova lista.DF 
- [] Exportar as colunas ( Year, Country, Area e Location)

SyntaxError: invalid syntax (2947645207.py, line 2)